In [87]:
import geopandas
import pandas
import matplotlib.pyplot as plt

In [88]:
countries_gdf = geopandas.read_file(r"G:\ONWR\_2021\องค์กรผู้ใช้น้ำ\tambon.gpkg", layer='tambon')

In [89]:
excel_input = pandas.read_excel(r"G:\ONWR\_2021\องค์กรผู้ใช้น้ำ\header_type_11_sizeS.xls")

In [95]:
gdf = geopandas.GeoDataFrame(excel_input, geometry=geopandas.points_from_xy(excel_input.ลองจิจูด, excel_input.ละติจูด),crs={'init': 'epsg:4326'})

In [100]:
#ide = geopandas.overlay(countries_gdf, gdf, how='identity')
#ide2 = geopandas.sjoin(countries_gdf, gdf, how="right", op='within')
ide2 = geopandas.sjoin(countries_gdf, gdf)

In [102]:
ide2

,PROV_NAMT,AMP_NAMT,TAM_NAMT,tam_id,code_id,FID_MainBa,MB_CODE,region,NBASIN_T,geometry,...,วันที่ตรวจสอบ,วันที่สำรวจแหล่งน้ำ,ความจุ (ล้านลูกบาศก์เมตร),ขนาดแหล่งน้ำ,ความลึก (เมตร),ระดับกักเก็บ (เมตร),ความสูงกักเก็บ (เมตร),หน่วยงานที่ได้รับการถ่ายโอน,ถ่ายโอนจากหน่วยงาน,สถานะการถ่ายโอน
212,สงขลา,สะเดา,ทุ่งหมอ,901005,901005.0,23,20,ใต้,ทะเลสาบสงขลา,"MULTIPOLYGON (((100.37883 6.81735, 100.37903 6...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
271,ตรัง,ห้วยยอด,ในเตา,920619,920619.0,26,22,ใต้,ภาคใต้ฝั่งตะวันตก,"MULTIPOLYGON (((99.72665 7.92771, 99.72669 7.9...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1455,กระบี่,คลองท่อม,เพหลา,810407,810407.0,26,22,ใต้,ภาคใต้ฝั่งตะวันตก,"MULTIPOLYGON (((99.17974 8.15858, 99.17973 8.1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1911,แพร่,สอง,สะเอียบ,540606,540606.0,7,08,เหนือ,ยม,"MULTIPOLYGON (((100.26867 18.81997, 100.26931 ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2671,กาญจนบุรี,บ่อพลอย,หนองรี,710303,710303.0,14,14,กลาง,แม่กลอง,"MULTIPOLYGON (((99.31907 14.63398, 99.31907 14...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4344,กำแพงเพชร,คลองลาน,โป่งน้ำร้อน,620302,620302.0,5,06,เหนือ,ปิง,"MULTIPOLYGON (((99.33873 16.38423, 99.33868 16...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4971,เพชรบุรี,แก่งกระจาน,ห้วยแม่เพรียง,760806,760806.0,19,18,กลาง,เพชรบุรี-ประจวบคีรีขันธ์,"MULTIPOLYGON (((99.33967 13.14265, 99.33981 13...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5013,ยะลา,เบตง,อัยเยอร์เวง,950204,950204.0,25,21,ใต้,ภาคใต้ฝั่งตะวันออกตอนล่าง,"MULTIPOLYGON (((101.40973 6.05436, 101.41019 6...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5082,ประจวบคีรีขันธ์,สามร้อยยอด,ศิลาลอย,770802,770802.0,19,18,กลาง,เพชรบุรี-ประจวบคีรีขันธ์,"MULTIPOLYGON (((99.46797 12.34992, 99.46829 12...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5850,ชลบุรี,บ้านบึง,หนองไผ่แก้ว,200208,200208.0,15,15,ตะวันออก,บางปะกง,"MULTIPOLYGON (((101.25849 13.24194, 101.26085 ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6314,สระแก้ว,ตาพระยา,ตาพระยา,270301,270301.0,16,16,ตะวันออก,โตนเลสาบ,"MULTIPOLYGON (((102.77933 14.05177, 102.77939 ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8142,มหาสารคาม,วาปีปทุม,หนองแสง,440901,440901.0,4,05,ตะวันออกเฉียงเหน,มูล,"MULTIPOLYGON (((103.36231 15.86697, 103.36232 ...",...,NaN,NaN,NaN,sizeS,NaN,NaN,NaN,NaN,NaN,NaN
8483,บึงกาฬ,เมืองบึงกาฬ,โนนสมบูรณ์,380102,380102.0,2,03,ตะวันออกเฉียงเหน,โขงตะวันออกเฉียงเหนือ,"MULTIPOLYGON (((103.65097 18.32482, 103.65095 ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
countries_gdf.head()

,PROV_NAMT,AMP_NAMT,TAM_NAMT,tam_id,code_id,FID_MainBa,MB_CODE,region,NBASIN_T,geometry
0,สงขลา,รัตภูมิ,เขาพระ,900909,900909.0,23,20,ใต้,ทะเลสาบสงขลา,"MULTIPOLYGON (((100.21039 6.98899, 100.20831 6..."
1,สงขลา,รัตภูมิ,เขาพระ,900909,900909.0,26,22,ใต้,ภาคใต้ฝั่งตะวันตก,"MULTIPOLYGON (((100.05704 7.10658, 100.05704 7..."
2,สงขลา,บางกล่ำ,แม่ทอม,901403,901403.0,23,20,ใต้,ทะเลสาบสงขลา,"MULTIPOLYGON (((100.45721 7.11704, 100.45724 7..."
3,สงขลา,เมืองสงขลา,บ่อยาง,900101,900101.0,24,20-is,ใต้,ทะเลสาบสงขลา,"MULTIPOLYGON (((100.59734 7.23755, 100.59741 7..."
4,พังงา,เมืองพังงา,บางเตย,820104,820104.0,26,22,ใต้,ภาคใต้ฝั่งตะวันตก,"MULTIPOLYGON (((98.58305 8.50352, 98.58307 8.5..."

In [94]:
plt.show()